server:
  port: 8000
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:8000/eureka
  server:
    response-cache-update-interval-ms: 10000
spring:
  application:
    name: eureka